# Site settings
title: Jonathan Porta
email: jonathan@jonathanporta.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in diy, electronics,
  programming, remote control and anything
  else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathan.porta.codes" # the base hostname & protocol for your site
twitter_username: jonathan_porta
github_username:  JonathanPorta

# Build settings
exclude: [vendor]
markdown: kramdown
kramdown:
  input: GFM
